import Foundation

// Checks for the pieces that need no Mac frameworks: the highlight cut, the board reader, the Stripe reader's key rules and the Twitch reader.
// Run on any machine with Swift:
//   swiftc -parse-as-library ClipMath.swift MeetingData.swift StripeData.swift StreamData.swift FeedData.swift ChatData.swift SecretFile.swift checks/DataChecks.swift -o /tmp/data-checks && /tmp/data-checks
@main struct DataChecks {
 static func main() {
  let hop = 0.25
  // A 30 second clip with a loud burst from 18 to 24 seconds keeps that burst plus a beat either side.
  var burst = [Float](repeating:0.02,count:120)
  for i in 72..<96 { burst[i] = 0.6 }
  let cut = ClipMath.highlight(levels:burst,hop:hop,maxLength:25)!
  precondition(abs(cut.start - 16.5) < 0.01 && abs(cut.end - 26.0) < 0.01)
  // Two bursts and a short limit: the bigger, later one wins.
  var two = [Float](repeating:0.02,count:120)
  for i in 12..<16 { two[i] = 0.3 }
  for i in 80..<92 { two[i] = 0.7 }
  let later = ClipMath.highlight(levels:two,hop:hop,maxLength:8)!
  precondition(later.start > 15 && later.length <= 8)
  // Silence: nothing to go on, so keep the most recent stretch.
  let quiet = ClipMath.highlight(levels:[Float](repeating:0,count:120),hop:hop,maxLength:25)!
  precondition(abs(quiet.end - 30) < 0.01 && abs(quiet.length - 25) < 0.01)
  precondition(ClipMath.highlight(levels:[],hop:hop,maxLength:25) == nil)
  // Whatever the input, the cut stays inside the clip and never exceeds the limit (or the 6 second minimum).
  for _ in 0..<500 {
   let n = Int.random(in:8...240)
   let levels = (0..<n).map { _ in Float.random(in:0...1) * (Bool.random() ? 0.05 : 0.9) }
   let limit = Double.random(in:8...40)
   let result = ClipMath.highlight(levels:levels,hop:hop,maxLength:limit)!
   precondition(result.start >= 0 && result.end <= Double(n) * hop + 1e-9 && result.length > 0 && result.length <= max(limit,6) + 1e-6)
  }

  // The board: owner, text and status are pulled apart; an indented line continues the item above; done items aren't open.
  let board = MeetingData.parse("# T\n_Last updated: x by y_\n## On the table\n- [A] one\n  more. Status: Done.\n- [B → C] two. Status: building\n## Q\n- hi\n")
  precondition(board.sections.count == 2 && board.updated == "x by y")
  let first = board.sections[0].items[0]
  precondition(first.owner == "A" && first.text == "one more." && first.isDone)
  precondition(board.sections[0].items[1].owner == "B → C" && board.openCount == 1)
  precondition(MeetingData.parse("").sections.isEmpty)

  // The room's message thread: tags are read, the Claude footer is dropped, a tagged "Matthew" from anyone but the owner's
  // account is ignored, and only a fine-grained GitHub key is accepted.
  let tagged = MeetingData.parseMessage(body:"**[Claude → GPT]** Please check this.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_")
  precondition(tagged.author == "Claude" && tagged.to == "GPT" && tagged.text == "Please check this.")
  precondition(MeetingData.parseMessage(body:"no tag").author == "?")
  let thread = #"[{"id":1,"body":"**[GPT]** hi","user":{"login":"matthewferreira818"},"created_at":"2026-10-05T12:00:00Z","html_url":"u"},{"id":2,"body":"**[Matthew]** spoof","user":{"login":"stranger"},"created_at":"2026-10-05T12:01:00Z","html_url":"v"}]"#.data(using:.utf8)!
  precondition(MeetingData.parseMessages(thread)?.map { $0.author } == ["GPT"])
  precondition(MeetingData.lastPage("<https://x?page=2>; rel=\"next\", <https://x?per_page=100&page=7>; rel=\"last\"") == 7)
  precondition(MeetingData.formatted(from:"Matthew",to:"Everyone",text:"hi") == "**[Matthew]** hi")
  precondition(MeetingData.tokenProblem("ghp_abc") != nil && MeetingData.tokenProblem("github_pat_abc") == nil)

  // Stripe: only a restricted read-only key is accepted.
  precondition(StripeData.keyProblem("sk_live_abc") != nil && StripeData.keyProblem("pk_live_abc") != nil)
  precondition(StripeData.keyProblem("rk_live_abc") == nil && StripeData.keyProblem("rk_test_abc") == nil)

  // Twitch: an empty stream list means offline, a live row is read, titles are checked, and refusals come out in plain words.
  precondition(StreamData.parseStream(["data":[]]) == nil)
  let liveRow: [String:Any] = ["data":[["type":"live","title":"Night run","game_name":"Minecraft","viewer_count":12,"started_at":"2026-10-05T20:00:00Z"]]]
  let onAir = StreamData.parseStream(liveRow)!
  precondition(onAir.title == "Night run" && onAir.game == "Minecraft" && onAir.viewers == 12 && onAir.startedAt != nil)
  let chan = StreamData.parseChannel(["data":[["broadcaster_id":"7","broadcaster_login":"me","broadcaster_name":"Me","title":"t","game_id":"27471","game_name":"Minecraft"]]])!
  precondition(chan.id == "7" && chan.gameID == "27471" && StreamData.parseChannel(["data":[]]) == nil)
  precondition(StreamData.parseCategories(["data":[["id":"1","name":"A"],["id":"","name":"skip"],["name":"no id"]]]).map { $0.name } == ["A"])
  let clipRows = StreamData.parseClips(["data":[["id":"c","url":"u","title":"T","view_count":3,"duration":28.5,"created_at":"2026-10-05T20:00:00Z"],["id":"d"]]])
  precondition(clipRows.count == 1 && clipRows[0].views == 3 && abs(clipRows[0].seconds - 28.5) < 0.001)
  precondition(StreamData.parseFollowerTotal(["total":41,"data":[]]) == 41 && StreamData.parseFollowerTotal([:]) == nil)
  precondition(StreamData.duration(7500) == "2h 05m" && StreamData.duration(420) == "7m")
  let t0 = Date(timeIntervalSince1970:1_000_000)
  precondition(StreamData.uptime(from:t0,to:t0.addingTimeInterval(20)) == "just started" && StreamData.uptime(from:t0,to:t0.addingTimeInterval(8040)) == "2h 14m")
  precondition(StreamData.titleProblem("  ") != nil && StreamData.titleProblem(String(repeating:"x",count:141)) != nil && StreamData.titleProblem("Night run") == nil)
  let bodyWithGame = try! JSONSerialization.jsonObject(with:StreamData.updateBody(title:" Hi ",gameID:"9")!) as! [String:String]
  precondition(bodyWithGame == ["title":"Hi","game_id":"9"])
  let bodyNoGame = try! JSONSerialization.jsonObject(with:StreamData.updateBody(title:"Hi",gameID:nil)!) as! [String:String]
  precondition(bodyNoGame == ["title":"Hi"])
  let onlyGame = try! JSONSerialization.jsonObject(with:StreamData.updateBody(title:nil,gameID:"9")!) as! [String:String]
  precondition(onlyGame == ["game_id":"9"] && StreamData.updateBody(title:nil,gameID:nil) == nil && StreamData.updateBody(title:"  ",gameID:"") == nil)
  // Friday's spoken category: an exact name wins, a single result is used, several close ones are not guessed.
  let mine = CategoryHit(id:"1",name:"Minecraft")
  precondition(StreamData.chooseCategory([CategoryHit(id:"2",name:"Minecraft Dungeons"),mine],query:" minecraft ") == .use(mine))
  precondition(StreamData.chooseCategory([mine],query:"mine") == .use(mine))
  precondition(StreamData.chooseCategory([],query:"x") == .none)
  precondition(StreamData.chooseCategory([CategoryHit(id:"2",name:"Minecraft Dungeons"),CategoryHit(id:"3",name:"Minecraft Legends"),CategoryHit(id:"4",name:"Minecraft Story"),CategoryHit(id:"5",name:"Minecraft Earth")],query:"mine") == .ask(["Minecraft Dungeons","Minecraft Legends","Minecraft Story"]))
  let marker = try! JSONSerialization.jsonObject(with:StreamData.markerBody(userID:"7",note:String(repeating:"n",count:200))!) as! [String:String]
  precondition(marker["user_id"] == "7" && marker["description"]?.count == 140)
  precondition(StreamData.encoded("Just Chatting & more") == "Just%20Chatting%20%26%20more")
  precondition(StreamData.explain(code:401,message:nil,doing:"x").contains("sign in again") && StreamData.explain(code:404,message:nil,doing:"add a marker").contains("VODs"))
  precondition(StreamData.explain(code:400,message:"bad",doing:"x").contains("bad"))
  // The Friday feed: blanks are skipped, whitespace is tidied, an immediate repeat counts once, the newest are kept, and the copy is plain text.
  let t1 = Date(timeIntervalSince1970:1_000_000)
  var feedLog = FeedFormat.appending([],who:"you",text:"  hello \n  there ",now:t1)
  precondition(feedLog.count == 1 && feedLog[0].text == "hello there")
  precondition(FeedFormat.appending(feedLog,who:"you",text:"   ",now:t1).count == 1)
  precondition(FeedFormat.appending(feedLog,who:"you",text:"hello there",now:t1.addingTimeInterval(5)).count == 1)
  precondition(FeedFormat.appending(feedLog,who:"you",text:"hello there",now:t1.addingTimeInterval(60)).count == 2)
  feedLog = FeedFormat.appending(feedLog,who:"friday",text:"Hi Matthew!",now:t1.addingTimeInterval(2))
  feedLog = FeedFormat.appending(feedLog,who:"action",text:"Clip: Clip made.",now:t1.addingTimeInterval(4))
  let copy = FeedFormat.transcript(feedLog)
  precondition(copy.contains("Matthew: hello there") && copy.contains("Friday: Hi Matthew!") && copy.contains("Action: Clip: Clip made.") && copy.components(separatedBy:"\n").count == 3)
  precondition(FeedFormat.transcript(feedLog,last:1).contains("Action:") && !FeedFormat.transcript(feedLog,last:1).contains("Friday:"))
  var many: [FeedEntry] = []
  for i in 0..<12 { many = FeedFormat.appending(many,who:"you",text:"m\(i)",now:t1.addingTimeInterval(Double(i) * 60),keep:10) }
  precondition(many.count == 10 && many.first?.text == "m2" && many.last?.text == "m11")
  precondition(FeedFormat.clean(String(repeating:"x",count:2000)).count == FeedFormat.maxLength)
  precondition(FeedFormat.actionLabel("set_stream_title") == "Title" && FeedFormat.actionLabel("scroll_page") == "Scroll" && FeedFormat.actionLabel("point_at") == "Pointer" && FeedFormat.actionLabel("zzz") == "Action")
  // The chat helper's rules: nothing posts right after starting, gaps and the hourly cap hold, the longest-waiting message goes
  // first, and bad text (empty, too long, starting with / or .) is never sent.
  let c0 = Date(timeIntervalSince1970:2_000_000)
  let a = ChatTimer(id:"a",name:"A",text:"Store link",minutes:20,enabled:true)
  let b = ChatTimer(id:"b",name:"B",text:"Prime",minutes:30,enabled:true)
  let off = ChatTimer(id:"c",name:"C",text:"Off",minutes:10,enabled:false)
  precondition(ChatPlan.next([a,b],lastPosted:[:],startedAt:c0,lastAny:nil,posts:[],now:c0.addingTimeInterval(4 * 60)) == nil)
  precondition(ChatPlan.next([a,b],lastPosted:[:],startedAt:c0,lastAny:nil,posts:[],now:c0.addingTimeInterval(10 * 60)) == nil)
  precondition(ChatPlan.next([a,b],lastPosted:[:],startedAt:c0,lastAny:nil,posts:[],now:c0.addingTimeInterval(21 * 60))?.id == "a")
  // Both due, neither posted yet: the one that is further past its own wait goes first. After "A" went out at 21 minutes, "B" is next.
  precondition(ChatPlan.next([a,b],lastPosted:[:],startedAt:c0,lastAny:nil,posts:[],now:c0.addingTimeInterval(55 * 60))?.id == "a")
  precondition(ChatPlan.next([a,b],lastPosted:["a":c0.addingTimeInterval(21 * 60)],startedAt:c0,lastAny:c0.addingTimeInterval(21 * 60),posts:[c0.addingTimeInterval(21 * 60)],now:c0.addingTimeInterval(55 * 60))?.id == "b")
  precondition(ChatPlan.next([a],lastPosted:["a":c0.addingTimeInterval(21 * 60)],startedAt:c0,lastAny:c0.addingTimeInterval(21 * 60),posts:[c0.addingTimeInterval(21 * 60)],now:c0.addingTimeInterval(38 * 60)) == nil)
  precondition(ChatPlan.next([a],lastPosted:["a":c0.addingTimeInterval(21 * 60)],startedAt:c0,lastAny:c0.addingTimeInterval(21 * 60),posts:[c0.addingTimeInterval(21 * 60)],now:c0.addingTimeInterval(42 * 60))?.id == "a")
  precondition(ChatPlan.next([off],lastPosted:[:],startedAt:c0,lastAny:nil,posts:[],now:c0.addingTimeInterval(99 * 60)) == nil)
  let hourBurst = (0..<6).map { c0.addingTimeInterval(Double(100 * 60 + $0 * 360)) }
  precondition(ChatPlan.next([a],lastPosted:[:],startedAt:c0,lastAny:hourBurst.last,posts:hourBurst,now:hourBurst.last!.addingTimeInterval(10 * 60)) == nil)
  precondition(ChatPlan.problem("") != nil && ChatPlan.problem("/ban someone") != nil && ChatPlan.problem(".timeout x") != nil && ChatPlan.problem(String(repeating:"x",count:501)) != nil && ChatPlan.problem("Hi!") == nil)
  precondition(ChatPlan.render("sub: twitch.tv/subs/{channel}",channel:"me") == "sub: twitch.tv/subs/me")
  precondition(ChatPlan.clampMinutes(2) == 10 && ChatPlan.clampMinutes(999) == 180 && ChatPlan.defaults().allSatisfy { ChatPlan.problem($0.text) == nil })
  precondition(ChatPlan.outcome(code:200,json:["data":[["message_id":"x","is_sent":true]]]).sent)
  precondition(!ChatPlan.outcome(code:200,json:["data":[["is_sent":false,"drop_reason":["code":"x","message":"held by AutoMod"]]]]).sent && ChatPlan.outcome(code:200,json:["data":[["is_sent":false,"drop_reason":["code":"x","message":"held by AutoMod"]]]]).note.contains("AutoMod"))
  precondition(ChatPlan.outcome(code:401,json:[:]).note.contains("sign in again") && !ChatPlan.outcome(code:429,json:[:]).sent)
  let chatBody = try! JSONSerialization.jsonObject(with:ChatPlan.sendBody(broadcaster:"1",sender:"2",message:"hi")!) as! [String:String]
  precondition(chatBody == ["broadcaster_id":"1","sender_id":"2","message":"hi"])
  // Secrets in private files: saved and read back, owner-only permissions, odd names can't escape the folder, empty is refused.
  let vault = FileManager.default.temporaryDirectory.appendingPathComponent("SecretFileCheck-\(UUID().uuidString)")
  precondition(SecretFile.write("GameCompanion.Test",Data("abc".utf8),in:vault) && SecretFile.read("GameCompanion.Test",in:vault) == Data("abc".utf8))
  let secretAttrs = try! FileManager.default.attributesOfItem(atPath:SecretFile.url("GameCompanion.Test",in:vault).path)
  let folderAttrs = try! FileManager.default.attributesOfItem(atPath:vault.path)
  precondition((secretAttrs[.posixPermissions] as? NSNumber)?.intValue == 0o600 && (folderAttrs[.posixPermissions] as? NSNumber)?.intValue == 0o700)
  precondition(SecretFile.write("GameCompanion.Test",Data("def".utf8),in:vault) && SecretFile.read("GameCompanion.Test",in:vault) == Data("def".utf8))
  precondition(SecretFile.fileName("../../etc/passwd") == ".._.._etc_passwd.secret" && !SecretFile.fileName("a/b").contains("/"))
  precondition(!SecretFile.write("empty",Data(),in:vault) && !SecretFile.exists("empty",in:vault))
  SecretFile.remove("GameCompanion.Test",in:vault)
  precondition(!SecretFile.exists("GameCompanion.Test",in:vault) && SecretFile.read("GameCompanion.Test",in:vault) == nil)
  try? FileManager.default.removeItem(at:vault)
  print("All data checks passed.")
 }
}
